Add Learn More button to Nonprofit in Project
hack4impact-uiuc/website pull request #86
Opened 2023-03-23 18:29 UTC by su-esther

## Status: :rocket: Ready

## Description

Adds a "Learn More" button that leads to the nonprofit's website in each H4I project's page

Fixes #85 

## Todos

## Screenshots

<img width="1104" alt="Screen Shot 2023-03-23 at 1 24 17 PM" src="https://user-images.githubusercontent.com/89177504/227311482-379e1251-7234-488a-adee-6a9ed331339e.png">

2023-03-23 18:36 UTC, SirajChokshi approved these changes
Looks good! Left one comment about a11y

2023-03-23 18:36 UTC, SirajChokshi commented on src/routes/projects/[slug]/+page.svelte
> +    type="secondary-custom"
We probably want to use a primary button here since there won't always be good contrast between the background the project's color. Should make this easier to read.

<img width="189" alt="Screenshot 2023-03-23 at 11 34 37 AM" src="https://user-images.githubusercontent.com/19193347/227314391-60349662-6c54-44e4-b282-a66124ca3d42.png">

2023-03-23 19:00 UTC, AndrewLester commented on src/routes/projects/[slug]/+page.svelte
> +    type="secondary-custom"
With this primary button you can use the `primary-custom` type and change the background color + text color to make it look like the scheme in `DoubleBanner`. Is that what you had in mind @SirajChokshi? The project-specific coloring for this looks pretty good imo.

My only concern with using the primary button here is that we'll eventually want a "visit site"/"view project" button that should be more visible, but that could have unique styling anyway.

2023-03-23 19:03 UTC, AndrewLester requested changes
Great work adding this, and nice job incorporating the project-specific colors. I didn't really consider that before, but it makes total sense.

Just the comments in the thread above I think, + do you mind adding back the newline between the sections on line 50, just to improve the readability of the page file?

2023-03-24 01:55 UTC, SirajChokshi commented on src/routes/projects/[slug]/+page.svelte
> +    type="secondary-custom"
Yup, I meany `project-custom`. I like the project-themed colors too :)

I think the secondary button in this type of lockup should be just text. At least to me, the border on the secondary button is too heavily weighted to make the label readable.

2023-03-24 19:48 UTC, SirajChokshi commented
<img width="280" alt="Screenshot 2023-03-24 at 12 46 59 PM" src="https://user-images.githubusercontent.com/19193347/227625102-cd3747e0-e07e-4543-b42a-b4267aa0b633.png">

This button is primary, but I was thinking we'd have the project color as the background and white as the text color (cc @AndrewLester)

2023-03-24 20:35 UTC, AndrewLester commented
Yep, I agree. For example, the "double banner"'s color scheme, used on the button:
<img width="443" alt="image" src="https://user-images.githubusercontent.com/23221268/227633405-d6fcb21f-b907-4726-9c7c-3420e8c54e16.png">
(Example color scheme of the button, just from the 7000 languages banner)

2024-01-24 07:58 UTC, AndrewLester approved these changes

2024-01-24 07:59 UTC, merged